import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Food Project</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/Logo.png" />
			</Head>

			<main className={styles.main}>
				<h1>Фуд РАБОТАЕТ</h1>
			</main>
		</Layout>
	);
}
